title: Python is Awesom!
author: Natnew
email: Natashanewboldlondon@gmail.com
description: > # This is a test:"
  This is a test (https://github.com/natnew) This is a test

# social links
twitter_username: natnew
github_username:  natashatweets2
show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
